"""ShopOrderItem link and production status

Revision ID: 32e18b9621db
Revises: d96bc5199b65
Create Date: 2026-08-31 18:12:40.244063
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '32e18b9621db'
down_revision: Union[str, None] = 'd96bc5199b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_order_items', sa.Column('customer_submitted_url', sa.String(length=2048), nullable=True))
    op.add_column('shop_order_items', sa.Column('final_verified_url', sa.String(length=2048), nullable=True))
    op.add_column('shop_order_items', sa.Column('link_status', sa.String(length=30), nullable=False, server_default='CUSTOMER_SUBMITTED'))
    op.add_column('shop_order_items', sa.Column('production_status', sa.String(length=30), nullable=False, server_default='NOT_PRODUCED'))
    op.drop_column('shop_order_items', 'destination_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_order_items', sa.Column('destination_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('shop_order_items', 'production_status')
    op.drop_column('shop_order_items', 'link_status')
    op.drop_column('shop_order_items', 'final_verified_url')
    op.drop_column('shop_order_items', 'customer_submitted_url')
    # ### end Alembic commands ###
