"""Add identity models and order updates

Revision ID: 4e2a052f42c5
Revises: 005_customization_activations
Create Date: 2026-08-28 08:37:46.436024
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '4e2a052f42c5'
down_revision: Union[str, None] = '005_customization_activations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_value', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_sessions_provider_value'), 'otp_sessions', ['provider_value'], unique=False)
    op.create_table('identity_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_value', sa.String(length=255), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_methods_customer_id'), 'identity_methods', ['customer_id'], unique=False)
    op.create_index(op.f('ix_identity_methods_provider_value'), 'identity_methods', ['provider_value'], unique=False)
    op.alter_column('destinations', 'url', new_column_name='source_url')
    op.add_column('destinations', sa.Column('nfc_redirect_url', sa.String(length=2048), nullable=True))
    op.add_column('destinations', sa.Column('qr_redirect_url', sa.String(length=2048), nullable=True))
    op.add_column('shop_orders', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.add_column('shop_orders', sa.Column('shipping_tracking_code', sa.String(length=100), nullable=True))
    op.add_column('shop_orders', sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_shop_orders_customer_id'), 'shop_orders', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'shop_orders', 'customer_identities', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_orders', type_='foreignkey')
    op.drop_index(op.f('ix_shop_orders_customer_id'), table_name='shop_orders')
    op.drop_column('shop_orders', 'shipped_at')
    op.drop_column('shop_orders', 'shipping_tracking_code')
    op.drop_column('shop_orders', 'customer_id')
    op.alter_column('destinations', 'source_url', new_column_name='url')
    op.drop_column('destinations', 'qr_redirect_url')
    op.drop_column('destinations', 'nfc_redirect_url')
    op.drop_index(op.f('ix_identity_methods_provider_value'), table_name='identity_methods')
    op.drop_index(op.f('ix_identity_methods_customer_id'), table_name='identity_methods')
    op.drop_table('identity_methods')
    op.drop_index(op.f('ix_otp_sessions_provider_value'), table_name='otp_sessions')
    op.drop_table('otp_sessions')
    op.drop_table('customer_identities')
    # ### end Alembic commands ###
