"""Add shipping_rules table

Revision ID: d96bc5199b65
Revises: 006_shipping_notifications
Create Date: 2026-08-31 06:19:12.102135
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd96bc5199b65'
down_revision: Union[str, None] = '006_shipping_notifications'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('postal_price', sa.Integer(), nullable=False),
    sa.Column('courier_available', sa.Boolean(), nullable=False),
    sa.Column('courier_price', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_rules_province'), 'shipping_rules', ['province'], unique=True)
    op.drop_index('ix_identity_methods_provider_value', table_name='identity_methods')
    op.add_column('shop_orders', sa.Column('shipping_cost', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_orders', 'shipping_cost')
    op.create_index('ix_identity_methods_provider_value', 'identity_methods', ['provider_value'], unique=False)
    op.drop_index(op.f('ix_shipping_rules_province'), table_name='shipping_rules')
    op.drop_table('shipping_rules')
    # ### end Alembic commands ###
