"""Add debug_code to OtpSession

Revision ID: f84133d70bfb
Revises: 4e2a052f42c5
Create Date: 2026-08-28 23:21:11.913071
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'f84133d70bfb'
down_revision: Union[str, None] = '4e2a052f42c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_code_key', 'cards', type_='unique')
    op.create_index('uix_identity_methods_provider_value', 'identity_methods', ['provider', 'provider_value'], unique=True)
    op.drop_index('ix_orders_business_id', table_name='orders')
    op.add_column('otp_sessions', sa.Column('debug_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_sessions', 'debug_code')
    op.create_index('ix_orders_business_id', 'orders', ['business_id'], unique=False)
    op.drop_index('uix_identity_methods_provider_value', table_name='identity_methods')
    op.create_unique_constraint('cards_code_key', 'cards', ['code'])
    # ### end Alembic commands ###
